name: rubocop-challenge
description: Run rubocop-challenger.
inputs:
  base_branch:
    description: Pull request base branch.
    required: false
    default: main
  mode:
    description: Mode to select deletion target.
    required: false
    default: random
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: r7kamura/rubocop-challenge-docker@v0.2.1
      with:
        base_branch: ${{ inputs.base_branch }}
        github_token: ${{ github.token }}
branding:
  color: red
  icon: git-pull-request
