name: rubocop-challenge
description: Run rubocop-challenger.
inputs:
  base_branch:
    description: Pull request base branch.
    required: false
    default: main
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - run: |
        echo /vendor/ >> .git/info/exclude
        git config remote.origin.url "git@github.com:${GITHUB_REPOSITORY}.git"
        gem install --install-dir=vendor/bundle --no-document rubocop_challenger
        vendor/bundle/bin/rubocop_challenger go \
          --base-branch="{{ inputs.base_branch }}" \
          --email="${GITHUB_ACTOR}@users.noreply.github.com" \
          --name="${GITHUB_ACTOR}"
      env:
        GITHUB_ACCESS_TOKEN: "${{ github.token }}"
      shell: bash
branding:
  color: red
  icon: git-pull-request
